### ISSUE TITLE
help please!

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/registration-form#1]
Whenever I add the grid system I can't match the screenshots, Where to  I put the grid and unit, and requires to join the mission and input[type"hidden"]?
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab so you only need one grid that surrounds 4 units where you have the Name/Age/Email/Physical Fitness - so you'll have to wrap these parts into a div with the class of "grid". Otherwise

Right before you close your form, add in this code  to fix your other error (which is just a remnant of stuff Thomas used to teach):
`    <input type="hidden" name="_subject" value="Request to join the mission">`

Hope this helps!

**Comment by Samirahajiragab** [comment]
Thank you soo much it helped a lot! :)
